apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-server
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
        - name: demo-server
          image: thanabodee2661/demo-server:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-server-service
  labels:
    app: demo-server
spec:
  type: NodePort
  selector:
    app: demo-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 9091

